! Testing dtio-generic-spec, R1208
!TODO-F08? INTERFACE READ (FORMATTED)
!TODO-F08? END INTERFACE READ (FORMATTED)
!TODO-F08? INTERFACE READ(UNFORMATTED )
!TODO-F08? END INTERFACE READ(UNFORMATTED )
!TODO-F08? INTERFACE WRITE( FORMATTED)
!TODO-F08? END INTERFACE WRITE( FORMATTED)
!TODO-F08? INTERFACE WRITE ( UNFORMATTED )
!TODO-F08? END INTERFACE WRITE ( UNFORMATTED )
END

