! Testing generic-spec, R1207
INTERFACE binky
END INTERFACE binky
!TODO-F08? INTERFACE OPERATOR(.abstract.)
!TODO-F08? END INTERFACE OPERATOR(.abstract.)
INTERFACE OPERATOR ( .le. )
END INTERFACE OPERATOR(.le.)
INTERFACE OPERATOR(-)
END INTERFACE OPERATOR(-)
INTERFACE ASSIGNMENT(=)
END INTERFACE ASSIGNMENT(=)
!TODO-F08? INTERFACE WRITE(UNFORMATTED)
!TODO-F08? END INTERFACE WRITE(UNFORMATTED)
END
