! Testing end-interface-stmt, R1204
INTERFACE
10 END INTERFACE
!TODO-F08 INTERFACE
!TODO-F08 END INTERFACE ASSIGNMENT ( = )
INTERFACE BINKY
END INTERFACE binky
!TODO-F08 INTERFACE
!TODO-F08 ENDINTERFACE write ( formatted )
END
