! Testing dtio-generic-spec, R1208
INTERFACE READ (FORMATTED)
END INTERFACE READ (FORMATTED)
INTERFACE READ(UNFORMATTED )
END INTERFACE READ(UNFORMATTED )
INTERFACE WRITE( FORMATTED)
END INTERFACE WRITE( FORMATTED)
INTERFACE WRITE ( UNFORMATTED )
END INTERFACE WRITE ( UNFORMATTED )
END

