!! R1204 end-interface-stmt
!     is END INTERFACE [ generic-spec ]
!

INTERFACE
10 END INTERFACE
INTERFACE
END INTERFACE ASSIGNMENT ( = )
INTERFACE BINKY
END INTERFACE binky
INTERFACE
ENDINTERFACE write ( formatted )
END
