! Testing generic-spec, R1207
INTERFACE binky
END INTERFACE binky
INTERFACE OPERATOR(.abstract.)
END INTERFACE OPERATOR(.abstract.)
INTERFACE OPERATOR ( .le. )
END INTERFACE OPERATOR(.le.)
INTERFACE OPERATOR(-)
END INTERFACE OPERATOR(-)
INTERFACE ASSIGNMENT(=)
END INTERFACE ASSIGNMENT(=)
INTERFACE WRITE(UNFORMATTED)
END INTERFACE WRITE(UNFORMATTED)
END
