!! R1204 end-interface-stmt
!     is END INTERFACE [ generic-spec ]
!

INTERFACE
10 END INTERFACE
!TODO-F08 INTERFACE
!TODO-F08 END INTERFACE ASSIGNMENT ( = )
INTERFACE BINKY
END INTERFACE binky
!TODO-F08 INTERFACE
!TODO-F08 ENDINTERFACE write ( formatted )
END
